using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Narendra4News.API.Data;
using Narendra4News.API.Models;
using Narendra4News.API.Services;
using System.Security.Claims;
using System.Text.RegularExpressions;
namespace Narendra4News.API.Controllers;
public record ArticleInput(string Title,string Slug,string? ShortDescription,string Content,string? FeaturedImageUrl,int CategoryId,int? MovieId,ArticleStatus Status,bool IsFeatured,bool IsTrending,string? SeoTitle,string? SeoDescription,string? SeoKeywords);
public record MovieInput(string Name,string Slug,string? Description,string? PosterUrl,string? HeroImageUrl,DateOnly? ReleaseDate,string? Hero,string? Director,string? Producer,string? ProductionHouse,string? Genre,string? Language,decimal? Budget,int? Runtime,string? Certification);
public record CollectionInput(DateOnly CollectionDate,int DayNumber,decimal? IndiaNet,decimal? IndiaGross,decimal? Overseas,decimal? WorldwideGross,decimal? OpeningDay,decimal? WeekendCollection,decimal? TotalCollection,string? Notes);
[ApiController][Route("api")]
public class ContentController(AppDbContext db,MediaService media) : ControllerBase {
 static string Slug(string value)=>Regex.Replace(value.Trim().ToLowerInvariant(),"[^a-z0-9-]+","-").Trim('-');
 static object Page<T>(List<T> items,int page,int size,int total)=>new {success=true,data=items,page,pageSize=size,total};
 [HttpGet("articles")] public async Task<IActionResult> Articles([FromQuery]string? category,[FromQuery]int page=1,[FromQuery]int size=12,CancellationToken ct=default){page=Math.Max(1,page);size=Math.Clamp(size,1,50);var q=db.Articles.AsNoTracking().Include(x=>x.Category).Where(x=>x.Status==ArticleStatus.Published&&x.PublishedDate<=DateTime.UtcNow);if(category!=null)q=q.Where(x=>x.Category.Slug==category);var count=await q.CountAsync(ct);return Ok(Page(await q.OrderByDescending(x=>x.PublishedDate).Skip((page-1)*size).Take(size).Select(x=>new{x.Id,x.Title,x.Slug,x.ShortDescription,x.FeaturedImageUrl,x.PublishedDate,x.Views,x.Likes,x.IsFeatured,x.IsTrending,Category=x.Category.Name,CategorySlug=x.Category.Slug,x.MovieId}).ToListAsync(ct),page,size,count));}
 [HttpGet("articles/{slug}")] public async Task<IActionResult> Article(string slug,CancellationToken ct){var x=await db.Articles.Include(x=>x.Category).FirstOrDefaultAsync(x=>x.Slug==slug&&x.Status==ArticleStatus.Published&&x.PublishedDate<=DateTime.UtcNow,ct);if(x is null)return NotFound(new{success=false,message="Article not found"});await db.Articles.Where(a=>a.Id==x.Id).ExecuteUpdateAsync(s=>s.SetProperty(a=>a.Views,a=>a.Views+1),ct);x.Views++;return Ok(new{success=true,data=new{x.Id,x.Title,x.Slug,x.ShortDescription,x.Content,x.FeaturedImageUrl,x.PublishedDate,x.UpdatedDate,x.Views,x.Likes,x.SeoTitle,x.SeoDescription,x.SeoKeywords,x.MovieId,Category=x.Category.Name,CategorySlug=x.Category.Slug}});}
 [HttpGet("categories")] public async Task<IActionResult> Categories(CancellationToken ct)=>Ok(new{success=true,data=await db.Categories.AsNoTracking().Where(x=>x.Active).OrderBy(x=>x.Name).ToListAsync(ct)});
 [HttpGet("movies")] public async Task<IActionResult> Movies(int page=1,int size=12,CancellationToken ct=default){page=Math.Max(1,page);size=Math.Clamp(size,1,50);var q=db.Movies.AsNoTracking();return Ok(Page(await q.OrderByDescending(x=>x.ReleaseDate).Skip((page-1)*size).Take(size).ToListAsync(ct),page,size,await q.CountAsync(ct)));}
 [HttpGet("movies/{slug}")] public async Task<IActionResult> Movie(string slug,CancellationToken ct){var x=await db.Movies.AsNoTracking().Include(x=>x.Collections).FirstOrDefaultAsync(x=>x.Slug==slug,ct);if(x is null)return NotFound(new{success=false,message="Movie not found"});var articles=await db.Articles.AsNoTracking().Where(a=>a.MovieId==x.Id&&a.Status==ArticleStatus.Published).OrderByDescending(a=>a.PublishedDate).Select(a=>new{a.Title,a.Slug,a.PublishedDate}).ToListAsync(ct);return Ok(new{success=true,data=new{movie=new{x.Id,x.Name,x.Slug,x.HeroImageUrl,x.PosterUrl,x.Description,x.ReleaseDate,x.Hero,x.Director,x.Producer,x.ProductionHouse,x.Genre,x.Language,x.Budget,x.Runtime,x.Certification,x.Views,Collections=x.Collections.OrderBy(c=>c.DayNumber).Select(c=>new{c.Id,c.CollectionDate,c.DayNumber,c.IndiaNet,c.IndiaGross,c.Overseas,c.WorldwideGross,c.OpeningDay,c.WeekendCollection,c.TotalCollection,c.Notes})},articles}});}
 [HttpGet("movies/{movieId:int}/collections")] public async Task<IActionResult> Collections(int movieId,CancellationToken ct)=>Ok(new{success=true,data=await db.Collections.AsNoTracking().Where(x=>x.MovieId==movieId).OrderBy(x=>x.DayNumber).ToListAsync(ct)});
 [HttpGet("search")] public async Task<IActionResult> Search(string q,int page=1,int size=12,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(q))return BadRequest(new{success=false,message="Enter a search term"});page=Math.Max(1,page);size=Math.Clamp(size,1,50);q=q.Trim();var a=await db.Articles.AsNoTracking().Where(x=>x.Status==ArticleStatus.Published&&(x.Title.Contains(q)||x.Content.Contains(q)||x.Category.Name.Contains(q))).OrderByDescending(x=>x.PublishedDate).Skip((page-1)*size).Take(size).Select(x=>new{x.Title,x.Slug,x.ShortDescription,x.FeaturedImageUrl,x.PublishedDate}).ToListAsync(ct);var m=await db.Movies.AsNoTracking().Where(x=>x.Name.Contains(q)).OrderBy(x=>x.Name).Take(size).Select(x=>new{x.Name,x.Slug,x.PosterUrl}).ToListAsync(ct);return Ok(new{success=true,data=new{articles=a,movies=m},page,pageSize=size});}
 [Authorize(Roles="Admin")][HttpGet("admin/dashboard")] public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(new{success=true,data=new{articles=await db.Articles.CountAsync(ct),published=await db.Articles.CountAsync(x=>x.Status==ArticleStatus.Published,ct),drafts=await db.Articles.CountAsync(x=>x.Status==ArticleStatus.Draft,ct),movies=await db.Movies.CountAsync(ct),views=await db.Articles.SumAsync(x=>(long)x.Views,ct)}});
 [Authorize(Roles="Admin")][HttpGet("admin/articles")] public async Task<IActionResult> AllArticles(CancellationToken ct)=>Ok(new{success=true,data=await db.Articles.AsNoTracking().OrderByDescending(x=>x.UpdatedDate).Take(100).ToListAsync(ct)});
 [Authorize(Roles="Admin")][HttpPost("articles")] public async Task<IActionResult> CreateArticle(ArticleInput input,CancellationToken ct){var slug=Slug(input.Slug);if(string.IsNullOrEmpty(slug)||string.IsNullOrWhiteSpace(input.Title)||!await db.Categories.AnyAsync(x=>x.Id==input.CategoryId,ct))return BadRequest(new{success=false,message="Invalid article or category"});if(await db.Articles.AnyAsync(x=>x.Slug==slug,ct))return Conflict(new{success=false,message="Slug already exists"});var x=new Article{AuthorId=User.FindFirstValue(ClaimTypes.NameIdentifier)};Assign(x,input,slug);db.Articles.Add(x);await db.SaveChangesAsync(ct);return Ok(new{success=true,data=x.Id,message="Article saved"});}
 [Authorize(Roles="Admin")][HttpPut("articles/{id:int}")] public async Task<IActionResult> UpdateArticle(int id,ArticleInput input,CancellationToken ct){var x=await db.Articles.FindAsync([id],ct);if(x is null)return NotFound();var slug=Slug(input.Slug);if(await db.Articles.AnyAsync(a=>a.Slug==slug&&a.Id!=id,ct))return Conflict(new{success=false,message="Slug already exists"});Assign(x,input,slug);await db.SaveChangesAsync(ct);return Ok(new{success=true,data=x.Id});}
 static void Assign(Article x,ArticleInput i,string slug){x.Title=i.Title;x.Slug=slug;x.ShortDescription=i.ShortDescription;x.Content=i.Content;x.FeaturedImageUrl=i.FeaturedImageUrl;x.CategoryId=i.CategoryId;x.MovieId=i.MovieId;x.IsFeatured=i.IsFeatured;x.IsTrending=i.IsTrending;x.SeoTitle=i.SeoTitle;x.SeoDescription=i.SeoDescription;x.SeoKeywords=i.SeoKeywords;if(i.Status==ArticleStatus.Published&&x.PublishedDate is null)x.PublishedDate=DateTime.UtcNow;x.Status=i.Status;x.UpdatedDate=DateTime.UtcNow;}
 [Authorize(Roles="Admin")][HttpDelete("articles/{id:int}")] public async Task<IActionResult> DeleteArticle(int id,CancellationToken ct){var x=await db.Articles.FindAsync([id],ct);if(x is null)return NotFound();x.Status=ArticleStatus.Archived;await db.SaveChangesAsync(ct);return Ok(new{success=true});}
 [Authorize(Roles="Admin")][HttpPost("categories")] public async Task<IActionResult> CreateCategory(Category input,CancellationToken ct){input.Id=0;input.Slug=Slug(input.Slug);db.Categories.Add(input);await db.SaveChangesAsync(ct);return Ok(new{success=true,data=input});}
 [Authorize(Roles="Admin")][HttpPut("categories/{id:int}")] public async Task<IActionResult> UpdateCategory(int id,Category input,CancellationToken ct){var x=await db.Categories.FindAsync([id],ct);if(x is null)return NotFound();x.Name=input.Name;x.Slug=Slug(input.Slug);x.Active=input.Active;await db.SaveChangesAsync(ct);return Ok(new{success=true});}
 [Authorize(Roles="Admin")][HttpDelete("categories/{id:int}")] public async Task<IActionResult> DeleteCategory(int id,CancellationToken ct){var x=await db.Categories.FindAsync([id],ct);if(x is null)return NotFound();x.Active=false;await db.SaveChangesAsync(ct);return Ok(new{success=true});}
 [Authorize(Roles="Admin")][HttpPost("movies")] public async Task<IActionResult> CreateMovie(MovieInput i,CancellationToken ct){var x=new Movie();Assign(x,i);if(string.IsNullOrWhiteSpace(x.Name)||string.IsNullOrWhiteSpace(x.Slug))return BadRequest();db.Movies.Add(x);await db.SaveChangesAsync(ct);return Ok(new{success=true,data=x.Id});}
 [Authorize(Roles="Admin")][HttpPut("movies/{id:int}")] public async Task<IActionResult> UpdateMovie(int id,MovieInput i,CancellationToken ct){var x=await db.Movies.FindAsync([id],ct);if(x is null)return NotFound();Assign(x,i);await db.SaveChangesAsync(ct);return Ok(new{success=true});}
 static void Assign(Movie x,MovieInput i){x.Name=i.Name;x.Slug=Slug(i.Slug);x.Description=i.Description;x.PosterUrl=i.PosterUrl;x.HeroImageUrl=i.HeroImageUrl;x.ReleaseDate=i.ReleaseDate;x.Hero=i.Hero;x.Director=i.Director;x.Producer=i.Producer;x.ProductionHouse=i.ProductionHouse;x.Genre=i.Genre;x.Language=i.Language;x.Budget=i.Budget;x.Runtime=i.Runtime;x.Certification=i.Certification;}
 [Authorize(Roles="Admin")][HttpDelete("movies/{id:int}")] public async Task<IActionResult> DeleteMovie(int id,CancellationToken ct){var x=await db.Movies.FindAsync([id],ct);if(x is null)return NotFound();db.Movies.Remove(x);await db.SaveChangesAsync(ct);return Ok(new{success=true});}
 [Authorize(Roles="Admin")][HttpPost("movies/{movieId:int}/collections")] public async Task<IActionResult> CreateCollection(int movieId,CollectionInput i,CancellationToken ct){if(!await db.Movies.AnyAsync(x=>x.Id==movieId,ct))return NotFound();var x=new CollectionRecord{MovieId=movieId};Assign(x,i);db.Collections.Add(x);await db.SaveChangesAsync(ct);return Ok(new{success=true,data=x.Id});}
 [Authorize(Roles="Admin")][HttpPut("collections/{id:int}")] public async Task<IActionResult> UpdateCollection(int id,CollectionInput i,CancellationToken ct){var x=await db.Collections.FindAsync([id],ct);if(x is null)return NotFound();Assign(x,i);await db.SaveChangesAsync(ct);return Ok(new{success=true});}
 static void Assign(CollectionRecord x,CollectionInput i){x.CollectionDate=i.CollectionDate;x.DayNumber=i.DayNumber;x.IndiaNet=i.IndiaNet;x.IndiaGross=i.IndiaGross;x.Overseas=i.Overseas;x.WorldwideGross=i.WorldwideGross;x.OpeningDay=i.OpeningDay;x.WeekendCollection=i.WeekendCollection;x.TotalCollection=i.TotalCollection;x.Notes=i.Notes;x.UpdatedDate=DateTime.UtcNow;}
 [Authorize(Roles="Admin")][HttpDelete("collections/{id:int}")] public async Task<IActionResult> DeleteCollection(int id,CancellationToken ct){var x=await db.Collections.FindAsync([id],ct);if(x is null)return NotFound();db.Collections.Remove(x);await db.SaveChangesAsync(ct);return Ok(new{success=true});}
 [HttpGet("media/file/{name}")] public async Task<IActionResult> Image(string name,CancellationToken ct){try{var (stream,type)=await media.Open(name,ct);Response.Headers.CacheControl="public,max-age=86400";return File(stream,type);}catch(Azure.RequestFailedException e) when(e.Status==404){return NotFound();}catch(ArgumentException){return NotFound();}}
 [Authorize(Roles="Admin")][HttpPost("media/upload")][RequestSizeLimit(6*1024*1024)] public async Task<IActionResult> Upload(IFormFile file,CancellationToken ct){try{var (name,url)=await media.Upload(file,ct);var item=new MediaItem{BlobName=name,Url=url};db.Media.Add(item);await db.SaveChangesAsync(ct);return Ok(new{success=true,data=item});}catch(ArgumentException e){return BadRequest(new{success=false,message=e.Message});}}
 [Authorize(Roles="Admin")][HttpGet("media")] public async Task<IActionResult> Media(CancellationToken ct)=>Ok(new{success=true,data=await db.Media.AsNoTracking().OrderByDescending(x=>x.CreatedAt).Take(100).ToListAsync(ct)});
 [Authorize(Roles="Admin")][HttpDelete("media/{id:int}")] public async Task<IActionResult> DeleteMedia(int id,CancellationToken ct){var x=await db.Media.FindAsync([id],ct);if(x is null)return NotFound();await media.Delete(x.BlobName,ct);db.Media.Remove(x);await db.SaveChangesAsync(ct);return Ok(new{success=true});}
}
