using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Narendra4News.API.Data;
using Narendra4News.API.Models;
using Narendra4News.API.Services;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContext<AppDbContext>(o=>{if(builder.Environment.IsDevelopment()&&builder.Configuration["DatabaseProvider"]=="Sqlite")o.UseSqlite(builder.Configuration.GetConnectionString("Sqlite")??"Data Source=narendra4news-dev.db");else o.UseSqlServer(builder.Configuration.GetConnectionString("Sql"));});
builder.Services.AddIdentityApiEndpoints<AppUser>(o=>{o.Password.RequiredLength=12; o.User.RequireUniqueEmail=true;}).AddRoles<IdentityRole>().AddEntityFrameworkStores<AppDbContext>();
builder.Services.AddAuthorization(); builder.Services.AddControllers().AddJsonOptions(o=>o.JsonSerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter())); builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen(); builder.Services.AddScoped<MediaService>();
var origins=builder.Configuration.GetSection("AllowedOrigins").Get<string[]>() ?? ["http://localhost:5173"]; builder.Services.AddCors(o=>o.AddDefaultPolicy(p=>p.WithOrigins(origins).AllowAnyHeader().AllowAnyMethod()));
var app=builder.Build(); if(app.Environment.IsDevelopment()){app.UseSwagger();app.UseSwaggerUI();} app.UseHttpsRedirection();app.UseDefaultFiles();app.UseStaticFiles();app.UseCors();app.UseAuthentication();app.UseAuthorization(); app.MapGroup("/api/auth").MapIdentityApi<AppUser>(); app.MapControllers();app.MapGet("/health",async (AppDbContext db,CancellationToken ct)=>await db.Database.CanConnectAsync(ct)?Results.Ok(new{status="healthy"}):Results.StatusCode(503));app.MapFallbackToFile("index.html");
using(var scope=app.Services.CreateScope()){var roles=scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>(); var users=scope.ServiceProvider.GetRequiredService<UserManager<AppUser>>(); var db=scope.ServiceProvider.GetRequiredService<AppDbContext>(); if(app.Environment.IsDevelopment()&&app.Configuration["DatabaseProvider"]=="Sqlite")await db.Database.EnsureCreatedAsync();else await db.Database.MigrateAsync(); foreach(var role in new[]{"Admin","User"}) if(!await roles.RoleExistsAsync(role)) await roles.CreateAsync(new IdentityRole(role)); var email=app.Configuration["ADMIN_EMAIL"];var pass=app.Configuration["ADMIN_PASSWORD"];if(!string.IsNullOrWhiteSpace(email)&&!string.IsNullOrWhiteSpace(pass)){var user=await users.FindByEmailAsync(email);if(user is null){user=new AppUser{UserName=email,Email=email,EmailConfirmed=true,MustChangePassword=true};var result=await users.CreateAsync(user,pass);if(!result.Succeeded)throw new InvalidOperationException(string.Join("; ",result.Errors.Select(x=>x.Description)));}if(!await users.IsInRoleAsync(user,"Admin"))await users.AddToRoleAsync(user,"Admin");} if(!await db.Categories.AnyAsync()){db.Categories.AddRange(new[]{"Telugu Updates","Trending","Box Office","Gossips","Reviews","Special","TRP","Records","Movies","OTT","Trailers","Events"}.Select(x=>new Category{Name=x,Slug=x.ToLowerInvariant().Replace(' ','-')}));await db.SaveChangesAsync();}}
app.Run();
