using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace Narendra4News.API.Models;
public class AppUser : IdentityUser { public bool MustChangePassword { get; set; } }
public enum ArticleStatus { Draft, Published, Archived }
public class Category { public int Id { get; set; } [MaxLength(100)] public string Name { get; set; } = ""; [MaxLength(120)] public string Slug { get; set; } = ""; public bool Active { get; set; } = true; }
public class Movie { public int Id { get; set; } [MaxLength(200)] public string Name { get; set; } = ""; [MaxLength(220)] public string Slug { get; set; } = ""; public string? HeroImageUrl { get; set; } public string? PosterUrl { get; set; } public string? Description { get; set; } public DateOnly? ReleaseDate { get; set; } public string? Hero { get; set; } public string? Director { get; set; } public string? Producer { get; set; } public string? ProductionHouse { get; set; } public string? Genre { get; set; } public string? Language { get; set; } public decimal? Budget { get; set; } public int? Runtime { get; set; } public string? Certification { get; set; } public int Views { get; set; } public List<CollectionRecord> Collections { get; set; } = []; }
public class CollectionRecord { public int Id { get; set; } public int MovieId { get; set; } public Movie Movie { get; set; } = null!; public DateOnly CollectionDate { get; set; } public int DayNumber { get; set; } public decimal? IndiaNet { get; set; } public decimal? IndiaGross { get; set; } public decimal? Overseas { get; set; } public decimal? WorldwideGross { get; set; } public decimal? OpeningDay { get; set; } public decimal? WeekendCollection { get; set; } public decimal? TotalCollection { get; set; } public string? Notes { get; set; } public DateTime CreatedDate { get; set; } = DateTime.UtcNow; public DateTime UpdatedDate { get; set; } = DateTime.UtcNow; }
public class Article { public int Id { get; set; } [MaxLength(250)] public string Title { get; set; } = ""; [MaxLength(270)] public string Slug { get; set; } = ""; [MaxLength(600)] public string? ShortDescription { get; set; } public string Content { get; set; } = ""; public string? FeaturedImageUrl { get; set; } public int CategoryId { get; set; } public Category Category { get; set; } = null!; public int? MovieId { get; set; } public Movie? Movie { get; set; } public string? AuthorId { get; set; } public DateTime? PublishedDate { get; set; } public DateTime UpdatedDate { get; set; } = DateTime.UtcNow; public ArticleStatus Status { get; set; } public bool IsFeatured { get; set; } public bool IsTrending { get; set; } public int Views { get; set; } public int Likes { get; set; } public string? SeoTitle { get; set; } public string? SeoDescription { get; set; } public string? SeoKeywords { get; set; } }
public enum ModerationStatus { Pending, Approved, Rejected }
public class Comment { public int Id { get; set; } public int ArticleId { get; set; } public Article Article { get; set; } = null!; public string UserId { get; set; } = ""; [MaxLength(2000)] public string Body { get; set; } = ""; public ModerationStatus Status { get; set; } = ModerationStatus.Pending; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class MediaItem { public int Id { get; set; } public string BlobName { get; set; } = ""; public string Url { get; set; } = ""; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
